### ISSUE TITLE
seems that i'm not even as good as a junior high stu......

### ISSUE THREAD

**Issue by uqsme** [Hayao0819/Hayao0819#1]
4.4k commits by this year, how crazy

**Comment by uqsme** [comment]
well, your profile shows that you are at the age of 16, but still in junior high. I search the Japanese school system but it said that 16-year-old students attend the senior high, 

so I wonder that how Japan gov determines school age, and how to divide a school year, could you pls tell me?

**Comment by Hayao0819** [comment]
I'm sorry I'm a high school student.
I forgot to update my profile when I entered  high school.

**Comment by Hayao0819** [comment]
I fixed my bio
